# Generated by Django 5.0.4 on 2024-05-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('breed', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
                ('hold', models.BooleanField()),
            ],
        ),
    ]
