# Generated by Django 5.0.4 on 2024-05-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0003_state_alter_pet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='hold',
            field=models.BooleanField(default=False),
        ),
    ]
